version: '3'

services:
    app:
      build: 
        context: ..
        dockerfile: Docker/Dockerfile
      image: anjanibarlapati/fingrow-app
      container_name: fingrow-app
      ports:
        - "3000:3000"
      networks: 
        - fingrow-network
      command: npm start 
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"] 
        interval: 30s 
        retries: 3    
        start_period: 10s  
        start_interval: 5s
        timeout: 30s 

networks:
  fingrow-network:
    name: fingrow-network



