pipeline {
    agent any

    environment {
        PATH = "${env.PATH}:/usr/local/bin/"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials') 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    dir('./backend') {
                        sh 'npm install'
                    }
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    dir('./backend') {
                        sh 'npm test -- --coverage --watchAll=false'
                    }
                }
            }
        }
        stage('Build Docker Image') {  
            steps{  
                dir('./backend') {
                    sh 'docker build . -t  anjanibarlapati/fingrow-server -f Docker/Dockerfile'     
                    echo 'Backend Image Build Completed'          
                }
            }           
        }

        stage('Login to Docker Hub') {         
            steps{   
                dir('./backend') {
                   sh 'docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW'  
	               echo 'Docker Login Completed'      
                }
            
            }           
        }               
        stage('Push Image to Docker Hub') {         
            steps{
                dir('./backend') {
                  	sh 'docker push anjanibarlapati/fingrow-server'   
                    echo 'Backend Image Push Completed'    
                }
            }           
        }
        stage('Pull Image from Docker Hub') {         
            steps{
                dir('./backend') {
                  	sh 'docker pull anjanibarlapati/fingrow-server'   
                    echo 'Backend Image Pull Completed'    
                }
            }           
        }
        stage('Run Container') {         
            steps{
                dir('./backend') {
                  	sh 'docker run --name fingrow-server -p 4321:4321 anjanibarlapati/fingrow-server:latest'   
                    echo 'Backend Container Run Completed'    
                }
            }           
        }
        stage('List Out Docker Images') {         
            steps{
                dir('./backend') {
                  	sh 'docker ps'   
                }
            }           
        }
        stage('Stop Backend Container') {         
            steps{
                dir('./backend') {
                  	sh 'docker stop fingrow-server'   
                    echo 'Backend Container Stop Completed'    
                }
            }           
        }
        stage('Remove Backend Container') {         
            steps{
                dir('./backend') {
                  	sh 'docker rm fingrow-server'   
                    echo 'Backend Container Remove Completed'    
                }
            }           
        }
        stage('List Out All Docker Images') {         
            steps{
                dir('./backend') {
                  	sh 'docker ps -a'   
                }
            }           
        }
    }
    post{
        always {  
          dir('./backend') {
            sh 'docker logout' 
            echo 'Docker Logout Completed'    
          }
        }      
    }
}
